src/objects/NotificatorLicense__c.object
<CustomObject>
    <fields>
        <fullName>InfoThreshold__c</fullName>
        <inlineHelpText>First notification will be sent if remaining licenses number will be below this threshold.</inlineHelpText>
        <label>Info Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Setting__c</fullName>
        <label>NotificatorSetting</label>
        <referenceTo>NotificatorSetting__c</referenceTo>
        <relationshipLabel>Notificator Licenses</relationshipLabel>
        <relationshipName>NotificatorLicenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>OK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warning</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WarningThreshold__c</fullName>
        <inlineHelpText>Final notification will be sent if remaining licenses number will be below this threshold.</inlineHelpText>
        <label>Warning Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Notificator License</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificator Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NotificatorSetting__c.object
<CustomObject>
    <fields>
        <fullName>recipient__c</fullName>
        <label>Error Notification Recipient Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Notificator Setting</label>
    <nameField>
        <label>NotificatorSetting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificator Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NotificatorStorage__c.object
<CustomObject>
    <fields>
        <fullName>InfoPercentageThreshold__c</fullName>
        <defaultValue>75</defaultValue>
        <inlineHelpText>First notification will be sent if current percent usage will be above this threshold.</inlineHelpText>
        <label>Percent Info Threshold</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Setting__c</fullName>
        <label>Notificator Setting</label>
        <referenceTo>NotificatorSetting__c</referenceTo>
        <relationshipLabel>Notificator Storages</relationshipLabel>
        <relationshipName>NotificatorStorages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>OK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warning</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WarningPercentageThreshold__c</fullName>
        <defaultValue>95</defaultValue>
        <inlineHelpText>Final notification will be sent if current percent usage will be above this threshold.</inlineHelpText>
        <label>Percent Warning Threshold</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Notificator Storage</label>
    <nameField>
        <label>Notificator Storage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificator Storages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NotificatorSingleton.cls
public class NotificatorSingleton {
    
    private static NotificatorSetting__c notificator;
    public static NotificatorSetting__c getNotificator() {
            if (notificator == null) init();
            return notificator;
    }
    
    private static List<StorageOCR> storages;
    public static List<StorageOCR> getStorages() {
            if (storages == null) init();
            return storages;
    }
  
    private static List<LicenseOCR> licenses;   
    public static List<LicenseOCR> getLicenses() {
            if (licenses == null) init();
            return licenses;
    }
    
    private static void init() {
        try {
            loadNotificator();
        } catch (System.QueryException ex) {
            initNewNotificator();
        }
    }

    private static void loadNotificator() {
        notificator = [
                SELECT recipient__c, (
                        SELECT ID, Name, InfoThreshold__c, WarningThreshold__c, Status__c, Setting__c
                        FROM NotificatorLicenses__r LIMIT 100
                ), (
                        SELECT ID, Name, InfoPercentageThreshold__c, WarningPercentageThreshold__c, Status__c, Setting__c
                        FROM NotificatorStorages__r LIMIT 100
                )
                FROM NotificatorSetting__c LIMIT 1
        ];

        licenses = new List<LicenseOCR>();
        for (NotificatorLicense__c nt: notificator.NotificatorLicenses__r) {
            licenses.add(new LicenseOCR(nt));
        }

        storages = new List<StorageOCR>();
        for (NotificatorStorage__c nt: notificator.NotificatorStorages__r) {
            storages.add(new StorageOCR(nt));
        }
    }

    public static void initNewNotificator() {
        notificator = new NotificatorSetting__c();
        initLicensesList();
        initStorageList();
    }

    private static void initLicensesList() {
        AggregateResult[] licenseNames = [SELECT Name FROM UserLicense GROUP BY Name LIMIT 100];
        licenses = new List<LicenseOCR>();

        for (AggregateResult name: licenseNames) {
            NotificatorLicense__c nl = new NotificatorLicense__c(Name = ''+name.get('Name'));
            LicenseOCR ocr = new LicenseOCR(nl);
            if(ocr.isValid) licenses.add(ocr);
        }
    }
	
    private static void initStorageList() {
        List<String> storageNames = new List<String> {
            StorageDictionary.DataByLanguage.get(UserInfo.getLanguage()),
            StorageDictionary.FileByLanguage.get(UserInfo.getLanguage())                
        };
        storages = new List<StorageOCR>();

        for (String name: storageNames) {
            NotificatorStorage__c ns = new NotificatorStorage__c(Name = name);
            StorageOCR ocr = new StorageOCR(ns);
            if(ocr.isValid) storages.add(ocr);              
        }
    }

}