src/objects/NotificatorLicense__c.object
<CustomObject>
    <fields>
        <fullName>InfoThreshold__c</fullName>
        <inlineHelpText>First notification will be sent if remaining licenses number will be below this threshold.</inlineHelpText>
        <label>Info Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>OK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warning</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WarningThreshold__c</fullName>
        <inlineHelpText>Final notification will be sent if remaining licenses number will be below this threshold.</inlineHelpText>
        <label>Warning Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Notificator License</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificator Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NotificatorSetting__c.object
<CustomObject>
    <label>Notificator Setting</label>
    <nameField>
        <label>NotificatorSetting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificator Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NotificatorJob_Test.cls
@isTest 
private class  NotificatorJob_Test {
    
    static testMethod void StorageLicenseCheck_UpdateAlertStatus() {
       NotificatorSetting__c notificator = NotificatorTestUtils.prepareTestNotificator();
        
        NotificatorLicense__c licenseToUpdate = [SELECT Id, Name, WarningThreshold__c, InfoThreshold__c, Status__c 
                                                 FROM NotificatorLicense__c WHERE Name='Salesforce'];
        system.assertEquals('OK',licenseToUpdate.Status__c);
        
        licenseToUpdate.InfoThreshold__c=19;
        update licenseToUpdate;

       Test.startTest();
		System.schedule('NotificatorJob_Test',
                        '0 0 0 15 3 ? 2022', 
                        new NotificatorJob());        
        Test.stopTest();
        
		licenseToUpdate = [SELECT Id, Name, WarningThreshold__c, InfoThreshold__c, Status__c 
                                                 FROM NotificatorLicense__c WHERE Name='Salesforce'];
        system.assertEquals('Info',licenseToUpdate.Status__c); 
    }

}